### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by xvyaward** [jiangsutx/SPMC_VideoSR#4]
Hi! I'm using python 3.5 version, so I changed
`print  ` to `print (~~)`
and
`xrange` to `range`.

And I got an error, 
`Testing path: ./data/test/calendar
number of testing frames: 31
Traceback (most recent call last):
  File "main_videosr_deploy_4x3f.py", line 111, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main_videosr_deploy_4x3f.py", line 108, in main
    model.test()
  File "main_videosr_deploy_4x3f.py", line 52, in test
    imgs = [inp[0] for i in range(idx0 - T, 0)]
TypeError: 'float' object cannot be interpreted as an integer`

Do you know how to solve this problem??

**Comment by jiangsutx** [comment]
I think you need to make T an integer in Line 50.
`T = int(num_frames / 2)` 

I will fix this problem soon.
